services:
  - type: worker
    name: xiaobobo-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REPORT_TARGET_CHAT_ID
        sync: false
      - key: TIMEZONE
        value: "Asia/Phnom_Penh"
      - key: REPORT_HOUR_MINUTE
        value: "09:00"
